//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class Interval
{
	private int s;
	private int e;
	public Interval ()
	{
	}

	public Interval(int start, int end)
	{
		s = start;
		e = end;
	}

	public int Start
	{
		get
		{
			return s;
		}
		set
		{
			s = value;
		}
	}

	public int End
	{
		get
		{
			return e;
		}
		set
		{
			e = value;
		}
	}

	public bool Contains(int i)
	{
		return ( i >= s && i < e );
	}

}

